// Auto-generated file - DO NOT EDIT MANUALLY
// This file is automatically generated by scripts/generate-music-list.js
// Run 'npm run generate-music' to regenerate this file

export const musicFiles: string[] = [
  "/music/La%20le%C3%A7on%20particuli%C3%A8re.mp3",
  "/music/die%20with%20smile.mp3"
];

// Export for easy access
export default musicFiles;
