// Auto-generated file - DO NOT EDIT MANUALLY
// This file is automatically generated by scripts/generate-music-list.js
// Run 'npm run generate-music' to regenerate this file

export const musicFiles: string[] = [
  "/music/La leçon particulière.m4a",
  "/music/die with smile.m4a"
];

// Export for easy access
export default musicFiles;
